Handle submodule update failure in install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -22,6 +22,11 @@ fi
 # Change to ssh remote ──────────────────────────────────────────────────────────────────────────────────────────────────
 git remote set-url origin git@github.com:danilrwx/dotfiles.git
 
+# Update submodules ──────────────────────────────────────────────────────────────────────────────────────────────────────
+if ! git submodule update --init --recursive; then
+  log "Failed to update submodules. Continue installation."
+fi
+
 # Create directories and synlinks to config files ───────────────────────────────────────────────────────────────────────
 mkdir -p $HOME/.config
 mkdir -p $HOME/.local/share
